target remote localhost:3333

* check file's information 
   readelf -h <archive>.a | grep 'Class\|File\|Machine'
   objdump -a *.a|grep 'file format'

* arm-none-eabi-gcc
  --specs=nosys.specs
  #LD_FLAG += --specs=rdimon.specs -lgcc -lc -lm -lrdimon



* Connect to OpenVPN over Shadowsock
Setup OpenVPN and Shadowsocks (Python / Node.js) on your server.

Setup OpenVPN client and Shadowsocks(Python / Node.js) on your local machine.

Connect Shadowsocks.

Add these lines to your .ovpn file:

socks-proxy 127.0.0.1 1080
route SHADOWSOCKS_SERVER_IP 255.255.255.255 net_gateway
Then connect OpenVPN.

Notice: only versions that support UDP relay support this feature.

find /home/andrew/velio/vdm2-firmware/src -path "/home/andrew/velio/vdm2-firmware/src/aws-iot-device-sdk-embedded-C" -prune -o  -path "/home/andrew/velio/vdm2-firmware/src/mbedtls" -prune -o -path "/home/andrew/velio/vdm2-firmware/src/mot/iot/include/aws_iot_json_utils.h" -prune -o -path "/home/andrew/velio/vdm2-firmware/src/mot/mbedtls/library/network.c" -prune -o -path "/home/andrew/velio/vdm2-firmware/src/mot/mbedtls/library/net_sockets.c" -prune -o -path "/home/andrew/velio/vdm2-firmware/src/mot/mbedtls/include/mbedtls/network.h" -prune -o -path "/home/andrew/velio/vdm2-firmware/src/mot/mbedtls/include/mbedtls/config.h" -prune -o -name "*.[chs]" -print > cscope.files

* vitrual box
sudo mount -t vboxsf gongxiang /mnt/shared


* indent
C-u M-|indent RET
